notifications:
  email:
    recipients:
      - zinoviev.denis@yandex.ru
      - nphoxconnect@gmail.com
  on_success: change
  on_failure: change

branches:
  only:
    - master
    - develop
    - test

os: linux
dist: trusty
sudo: enabled

language: go
go:
  - "1.10"
  
install: true

script:
  - cd ./static-server
  - go get -d ./...
  - go build
  - go vet .
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
